### ISSUE TITLE
[enahancement]

### ISSUE THREAD

**Issue by vonovak** [alekhurst/react-native-elevated-view#1]
hi! thanks for the component! I would like to ask you to add a license file so we know how the component can be used.

Also, the elevation prop isn't very likely to change, but I noticed the styles are being recomputed on every render, and on both platforms while it would be probably sufficient to compute them once and only on ios. (but it's not a big deal)

**Comment by alekhurst** [comment]
Hi vonovak, thanks for reaching out!

I have just added a license to this repo.

As for the styling recommendation, I wanted to mimic the React Native elevation prop as closely as possible. It is an extremely light computation, so it should not effect perf in any scenario.

**Comment by vonovak** [comment]
right, it's just the matter of making it slightly prettier. btw 
```
let iosShadowElevation = {
      shadowColor: 'black',
    };
```
at line 7 seems to be overwritten by the switch
