### ISSUE TITLE
Cant even import

### ISSUE THREAD

**Issue by peferb** [alekhurst/react-native-elevated-view#10]
With only `import ElevatedView from 'react-native-elevated-view'` in my file i get "undefined is not an object (evaluating '_react3.default.PropTypes.number')"

doesnt even need to use `<ElevatedView>` to get the error.

**Comment by alekhurst** [comment]
We've just updated to use the `prop-types` instead of `React.PropTypes`. This should fix your issue. Please feel free to re-open if it does not.
