### ISSUE TITLE
[QUESTION] I want the shadow only on the bottom, How do I get that?

### ISSUE THREAD

**Issue by Jose4gg** [alekhurst/react-native-elevated-view#13]

**Comment by deadcoder0904** [comment]
I think its not possible in React Native. Below is an example without using this lib. Only all sides AFAIK using

```js
{
    shadowColor: '#999',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 5,
    shadowOpacity: 1.0,
    // everything above only works for iOS
    elevation: 24, // only for Android 5.0+
}
```

**Comment by alekhurst** [comment]
The above answer is correct (this is how this library works internally). 

If you pass this in as style to the `<ElevatedView style={styles.customShadow} elevation={1} />`, the custom style should override the default styles.
