### ISSUE TITLE
Cast shadow on top?

### ISSUE THREAD

**Issue by FezVrasta** [alekhurst/react-native-elevated-view#14]
I'd like to add a shadow to a bottom bar, but to do so the shadow should be casted on top instead of bottom. How can I specify the orientation of the shadow?

**Comment by hansfpc** [comment]
Same question here

**Comment by alekhurst** [comment]
Hello, you can use react native shadow props https://facebook.github.io/react-native/docs/shadow-props.html, but that is out of the scope of this library

**Comment by FezVrasta** [comment]
but I use this library exactly because I don't want to use the RN shadow-props... I want an easy way to use the Material Design shadows 🤷‍♀️

Why is it out of scope? My use case is legit
