### ISSUE TITLE
on Android, backgroundColor is required to show the shadow

### ISSUE THREAD

**Issue by FezVrasta** [alekhurst/react-native-elevated-view#15]
You should set it to some color (white?) to allow Android to render the shadow, otherwise nothing will render.

**Comment by connor-ricks** [comment]
Why did you close this?

I'm having this issue as well.

**Comment by FezVrasta** [comment]
7d380ca6a2b6c2659980b41b2b0aa29779e1b2fa

**Comment by connor-ricks** [comment]
I feel like this is a hackish solution.

Why doesn't the shadow appear unless the background color is set?

**Comment by FezVrasta** [comment]
That's a limitation of Android

**Comment by connor-ricks** [comment]
Bah Humbug! Okay, now worries! Thanks for clearing this up.
