### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by DavidNorena** [alekhurst/react-native-elevated-view#17]
Can you please guys include typescript support !?

Thank you and awesome !

**Comment by fhelwanger** [comment]
I created this PR to add the definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24506

**Comment by DavidNorena** [comment]
Thank you so much @fhelwanger, I'll wait unitl it gets approved, again thank you so much !

**Comment by DavidNorena** [comment]
Thanks [its published now](https://www.npmjs.com/package/@types/react-native-elevated-view)
