### ISSUE TITLE
FlatList items not clickable within ElevatedView

### ISSUE THREAD

**Issue by paulhristea** [alekhurst/react-native-elevated-view#18]
I had a FlatList on an ElevatedView with elevation = 1 and I found it impossible to make the FlatList items clickable in any way. I tried setting onPress on an enclosing TouchableWithoutFeedback and on the ListItem itself, nothing worked until I removed the ElevatedView from underneath the FlatList. The onClick events seem to be swallowed up by the ElevatedView somehow.
If the issue is not obvious, I might provide some code to reproduce it. Just let me know.
Thanks!

**Comment by alekhurst** [comment]
Hi Paul, thanks for submitting this issue. It seems like you were able to isolate it to this component. It would be awesome if you could submit a PR to fix this! This repo only really has one file containing very little complexity, so providing the code to repro this issue might take the same amount of time as fixing it.
