### ISSUE TITLE
Cannot calculate shadow efficiently

### ISSUE THREAD

**Issue by koloff** [alekhurst/react-native-elevated-view#19]
Hello! I need my elevated views to be transparent. But then I am getting the following "ADVICE":

ADVICE) View #335 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.

**Comment by alekhurst** [comment]
This could be because you are manually setting `backgroundColor: 'transparent'`
