### ISSUE TITLE
zIndex and Elevation

### ISSUE THREAD

**Issue by i8wu** [alekhurst/react-native-elevated-view#2]
Hey, I've noticed that in iOS for my ElevatedView > TextInput component, I needed to add zIndex to the ElevatedView to match the elevation number or else it wouldn't be selectable. Using RN0.39.0. Haven't had much time to look into it more but my fix works if anybody comes across this issue.

**Comment by JReinhold** [comment]
I haven't been able to reproduce this problem.

Tried this component on iOS simulator:
`<ElevatedView elevation={5}>
				<TextInput
					style={
						{
							backgroundColor: '#FFFFFF',
							width: 200,
							height: 80,
						}
					}
				/>
			</ElevatedView>`

Selecting the TextInput and writing in it worked fine, so did selecting the text.

I'm on RN0.41.0, maybe that's the difference.

**Comment by i8wu** [comment]
We'll be upgrading to RN0.40+ in a few weeks and I'll try to revisit this if I have time. I'm fine with closing this issue for now. Just posted it here in case anyone else ran across it.

**Comment by alekhurst** [comment]
I was not able to reproduce this. If you come across it again and can repro, feel free to re-open.
