### ISSUE TITLE
Further elevation

### ISSUE THREAD

**Issue by 0xs34n** [alekhurst/react-native-elevated-view#4]
On material guidelines: https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows

elevation has a maximum of 24

**Comment by JReinhold** [comment]
That makes sense. I remember to have read somewhere, that the elevation prop in React-Native can only be 0-5, but I cannot find that information again. If it is the case, then I don't think there's much for us to do here, then it is an underlying problem with RN, and not ElevatedView.

However if that is not the case, I completely agree that it should be possible to set elevation to 24 in the ElevatedView aswell.

I will do some research into this.
