### ISSUE TITLE
feature: Support Material Design components as first class components

### ISSUE THREAD

**Issue by JReinhold** [alekhurst/react-native-elevated-view#7]
Now that we can elevate views up to 24, it's possible to better support material design components.

I've been thinking about making default components for all the Material Design components listed in their [documentation](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android). Eg. implementing a `<NavDrawer />` component which internally is a simple wrapper for `<ElevatedView elevation={16} />`.

This would make it easier for developers to implement (parts of) the Material Design guidelines, as they would only have to import the specified component, and not figure out the correct elevation on their own.

Another upside is the improved readability this could produce. Compare the following code, producing an AppBar, a Card and a Floating Action Button:
**Using current implementation**
```
<ElevatedView elevation={4}>
  ...
</ElevatedView>
<ElevatedView elevation={2}>
  ...
</ElevatedView>
<ElevatedView elevation={6}>
  ...
</ElevatedView>
```

**Using proposed implementation**
```
<AppBar>
  ...
</AppBar>
<Card>
  ...
</Card>
<FloatingActionButton>
  ...
</FloatingActionButton>
```

For the most part no one would ever change the component-type at runtime, like from a Dialog to a FAB, which is why I propose this implementation, and not something like `<ElevatedView type="modal" />`. However there are edge cases like raising and lowering a button, but I'm sure we can figure that out.

But this feature would expand ElevatedView's responsibility to support Material Design, and only @alekhurst knows if that is a path we want to follow. Would you rather have ElevatedView as a simple, single responsibility library, or would you use this unique cross-platform shadow-api to support more shadow-dependent features?

**Comment by JReinhold** [comment]
@alekhurst any thoughts?

**Comment by alekhurst** [comment]
@jreinhold This is a great idea, I think a lot of people would find this useful. It seems orthogonal to this repo though, and would make more sense as its own repo. I'd be happy to spin it up here, or help out if you want to create it off of your account.

**Comment by alekhurst** [comment]
Hey @JReinhold I've created the repo and done the plumbing at https://github.com/alekhurst/react-native-materials. I'm going to work on the README over the next few days. 

I could use some help getting all of the correct material components with their respective elevations into the repo.

**Comment by JReinhold** [comment]
Oh cool.! If I have time I might look into it during the weekend
